/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author richard
 */
public class InternalReporte extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalReporte
     */
    public InternalReporte() {
        initComponents();
        panel1.setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOpciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdbProductos = new javax.swing.JRadioButton();
        rdbSalida = new javax.swing.JRadioButton();
        rdbEntrada = new javax.swing.JRadioButton();
        contenedor = new javax.swing.JLayeredPane();
        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Reportes");

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Seleccione el tipo de reporte", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        grupoOpciones.add(rdbProductos);
        rdbProductos.setText("Productos");
        rdbProductos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbProductosStateChanged(evt);
            }
        });

        grupoOpciones.add(rdbSalida);
        rdbSalida.setText("Salidas");
        rdbSalida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbSalidaStateChanged(evt);
            }
        });

        grupoOpciones.add(rdbEntrada);
        rdbEntrada.setText("Entradas");
        rdbEntrada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbEntradaStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rdbProductos)
                .addGap(71, 71, 71)
                .addComponent(rdbSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(rdbEntrada)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbProductos)
                    .addComponent(rdbSalida)
                    .addComponent(rdbEntrada))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        contenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel1.setPreferredSize(new java.awt.Dimension(372, 113));

        jLabel1.setText("Seleccione el reporte que desee visualizar");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        panel1.setBounds(0, 0, 460, 150);
        contenedor.add(panel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbSalidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbSalidaStateChanged
        // TODO add your handling code here:
        if(rdbSalida.isSelected()){
            contenedor.removeAll();
            contenedor.repaint();
            javax.swing.JPanel salida= new PanelRepSalida();
            salida.setLocation(0, 0);
            contenedor.add(salida);
        }
    }//GEN-LAST:event_rdbSalidaStateChanged

    private void rdbProductosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbProductosStateChanged
        // TODO add your handling code here:
        if(rdbProductos.isSelected()){
            contenedor.removeAll();
            contenedor.repaint();
            javax.swing.JPanel productos= new PanelRepProductos();
            productos.setLocation(0, 0);
            contenedor.add(productos);
        }
    }//GEN-LAST:event_rdbProductosStateChanged

    private void rdbEntradaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbEntradaStateChanged
        // TODO add your handling code here:
        if(rdbEntrada.isSelected()){
            contenedor.removeAll();
            contenedor.repaint();
            javax.swing.JPanel entrada= new PanelRepEntrada();
            entrada.setLocation(0, 0);
            contenedor.add(entrada);
        }
    }//GEN-LAST:event_rdbEntradaStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane contenedor;
    private javax.swing.ButtonGroup grupoOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JRadioButton rdbEntrada;
    private javax.swing.JRadioButton rdbProductos;
    private javax.swing.JRadioButton rdbSalida;
    // End of variables declaration//GEN-END:variables
}
