/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Compra;
import Clases.Producto;
import Clases.Venta;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author richard
 */
public class InternalBuscador extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalBuscador
     */
    public InternalBuscador() {
        initComponents();
        this.cargarTablaPro();
        this.cargarTablaComp();
        this.cargarTablaVenta();
    }
    
    private void setAnchoColumnas(JTable tabla){
        JViewport scroll =  (JViewport) tabla.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna=0;
        TableColumnModel modeloColumna = tabla.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch(i){
                case 0: anchoColumna = (13*ancho)/100;
                        break;
                case 1: anchoColumna = (90*ancho)/100;
                        break;
                case 2: anchoColumna = (35*ancho)/100;
                        break;
                case 3: anchoColumna = (40*ancho)/100;
                        break;
                case 4: anchoColumna = (40*ancho)/100;
                        break;
            }                     
            columnaTabla.setPreferredWidth(anchoColumna);           
        }
    }
    
    private void cargarTablaPro(){
        AbstractTableModel model= Producto.gestionProducto();
        this.tablaProducto.setModel(model);
        this.tablaProducto.getTableHeader().setReorderingAllowed(false);
        this.tablaProducto.setDefaultRenderer(Boolean.class, new MyTableRenderer.ImageRenderer());
        TableColumn colum= this.tablaProducto.getColumnModel().getColumn(4);
        colum.setCellRenderer(new MyTableRenderer.BotonProductoRenderer());
        colum.setCellEditor(new MyTableRenderer.BotonProductoEditor(tablaProducto));
        this.setAnchoColumnas(tablaProducto);
    }
    
    private void cargarTablaComp(){
        DefaultTableModel model= Compra.getCompras();
        this.tablaCompra.setModel(model);
        this.tablaCompra.getTableHeader().setReorderingAllowed(false);
        TableColumn colum= this.tablaCompra.getColumnModel().getColumn(3);
        colum.setCellRenderer(new MyTableRenderer.botonCompraVentaRenderer());
        colum.setCellEditor(new MyTableRenderer.BotonCompraVentaEditor(this.tablaCompra, "Compra"));
        this.setAnchoColumnas(tablaCompra);
    }
    
    private void cargarTablaVenta(){
        DefaultTableModel model= Venta.getVentas();
        this.tablaVenta.setModel(model);
        this.tablaVenta.getTableHeader().setReorderingAllowed(false);
        TableColumn colum= this.tablaVenta.getColumnModel().getColumn(3);
        colum.setCellRenderer(new MyTableRenderer.botonCompraVentaRenderer());
        colum.setCellEditor(new MyTableRenderer.BotonCompraVentaEditor(tablaVenta, "Venta"));
        this.setAnchoColumnas(tablaVenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCompra = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Administrador");

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProducto);

        jTabbedPane1.addTab("Productos", jScrollPane1);

        tablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaCompra);

        jTabbedPane1.addTab("Compras", jScrollPane2);

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaVenta);

        jTabbedPane1.addTab("Ventas", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaCompra;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTable tablaVenta;
    // End of variables declaration//GEN-END:variables
}
