/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Reportes.IProductos;
import javax.swing.JOptionPane;

/**
 *
 * @author richard
 */
public class PanelRepProductos extends javax.swing.JPanel {

    /**
     * Creates new form PanelRepProductos
     */
    public PanelRepProductos() {
        initComponents();
        this.setSize(374, 132);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgProductos = new javax.swing.ButtonGroup();
        rbtnActivo = new javax.swing.JRadioButton();
        rbtnInactivo = new javax.swing.JRadioButton();
        rbtnTodos = new javax.swing.JRadioButton();
        btnAceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Reporte productos"));
        setPreferredSize(new java.awt.Dimension(372, 113));

        btgProductos.add(rbtnActivo);
        rbtnActivo.setText("Activos");

        btgProductos.add(rbtnInactivo);
        rbtnInactivo.setText("Inactivos");

        btgProductos.add(rbtnTodos);
        rbtnTodos.setText("Todos");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnActivo)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(rbtnInactivo)
                        .addGap(77, 77, 77)
                        .addComponent(rbtnTodos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnActivo)
                    .addComponent(rbtnInactivo)
                    .addComponent(rbtnTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if(rbtnActivo.isSelected()){
            new IProductos().verProductos("1", "1");
        }
        else{
            if(rbtnInactivo.isSelected()){
                new IProductos().verProductos("0", "0");
            }
            else{
                if(rbtnTodos.isSelected()){
                    new IProductos().verProductos("1", "0");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Debe seleccionar una opción", "Error", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgProductos;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JRadioButton rbtnActivo;
    private javax.swing.JRadioButton rbtnInactivo;
    private javax.swing.JRadioButton rbtnTodos;
    // End of variables declaration//GEN-END:variables
}
